-- Category: FUNCTION
CREATE FUNCTION FN_GET_CONFIG_VALUE (
    @ParamName NVARCHAR(100)
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
    DECLARE @Val NVARCHAR(MAX);
    SELECT @Val = ParamValue FROM SYS_CONFIG WHERE ParamName = @ParamName;
    RETURN @Val;
END;