CREATE TABLE SYS_CONFIG (
    ConfigId INT PRIMARY KEY IDENTITY(1,1),
    ParamName NVARCHAR(100) UNIQUE,
    ParamValue NVARCHAR(MAX),
    LastUpdate DATETIME DEFAULT GETDATE(),
    UpdatedBy NVARCHAR(100)
);