CREATE TABLE CUSTOMER_LIMITS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_NAME NVARCHAR(100),
    TOTAL_LIMIT DECIMAL(18,2),
    USED_LIMIT DECIMAL(18,2),
    CREATED_DATE DATETIME DEFAULT GETDATE()
);