name: Jira Automation - Create Branch
on:
  repository_dispatch:
    types: [create-jira-branch]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and Push Branch
        run: |
          # Jira'dan gelen verileri değişkenlere al
          ISSUE_KEY="${{ github.event.client_payload.issue_key }}"
          SUMMARY="${{ github.event.client_payload.summary }}"
          
          # Branch ismini temizle (Türkçe karakter, boşluk ve özel karakterleri düzelt)
          CLEAN_SUMMARY=$(echo "$SUMMARY" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--/-/g' | cut -c1-30)
          BRANCH_NAME="feature/${ISSUE_KEY}-${CLEAN_SUMMARY}"
          
          echo "Olusturulacak branch: $BRANCH_NAME"
          
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
